### ISSUE TITLE
Path of titans bug 

### ISSUE THREAD

**Issue by N30Draco** [Auhrus/pathoftitans-docker-server#3]
**Describe the error as best you can**
There appears to be a some type of visual bug that leaves a blurry trail when your camera is facing the darker parts of the cliff.

**How to reproduce it (if it is)**
1. Go to the location and move your camera around while facing the the area. 

**What should actually happen**

The moving part of your body should leave some type of trail 
**Have you tried re-downloading/re-setting up the image yet?**
Yes

**Specs**
- Operating System: PlayStation 5
- Version: 
- Docker Version: 

**Screenshots**
![7186BC47-8D84-4524-A94C-3F3EA58BC742](https://user-images.githubusercontent.com/121743402/210163487-30b1c46c-6081-4c30-a9d8-952c295342b6.png)

![0112481C-558E-4701-99D4-C10DA18404D7](https://user-images.githubusercontent.com/121743402/210162923-459184a6-64c3-4ce4-9d6d-a3d47ef51c93.png) 

Video clip:
https://drive.google.com/file/d/1g2oIoH9ASMUtw6acpamYHiXGYVeTqPbF/view?usp=drivesdk

**Additional Stuff**
Add more information about the problem here.
The coordinates are (X=138753.027936,Y=153319.323362,Z=799.615168 
My account username name is XxNeo_DracoxX 
My ID is 914-487-389

**Comment by Auhrus** [comment]
Hi👋, unfortunately you have landed in the wrong repository. This repository is about a server for PathofTitans not about the game itself. Also, I am not associated with PathofTitans or Alderon Games. This bug you reported has nothing to do with the Docker container provided by this repository. Please re-post your bug report here at https://github.com/Alderon-Games/pathoftitans-bugs/issues and answer the questions asked there in the template. This is the official repository of Alderon Games which is also linked in the game itself to report bugs.

Here you can find a description of what you have to consider when reporting.
https://github.com/Alderon-Games/pathoftitans-bugs/wiki/Reporting-Bugs-&-Format
