### ISSUE TITLE
logged in under map

### ISSUE THREAD

**Issue by JuneduXisosaFegore** [Auhrus/pathoftitans-docker-server#4]
**Describe the error as best you can**
I was killed, and logged out to wait for someone to get to ws. i logged back in and it took me under map. Logged out then logged back in and spawned in the cave, Repeated the log out to test it and came back in under map rinsed and repeat,

**How to reproduce it (if it is)**
1.  shown in video

**What should actually happen**
Not spawn through map

When did this issue occur?3/324:
Your Alderon Games display nameJuneduXisosaFegore:
Your Alderon Games ID900-737-175:
PlatformPC:
Did this occur on a community or official serverofficial server:
Did you, in the same game session, previously play on a community server if you experienced this issue on official serversno only on official server:
Server ID/Name (Official Server ID can be found on the Social Menu)* Server_221537bb-f5f9-4291-8328e-1b45coae5749*:
Server population (if Able)81:
A short clip of the issue clip is above

https://github.com/Auhrus/pathoftitans-docker-server/assets/162003260/8e65cec6-7b83-4bc0-a949-ce07b2424a37

**Comment by JuneduXisosaFegore** [comment]
i had to shorten the clip but i have a longer clip that GitHub wouldn't let me upload. if i am able to get a ksin form this can i please have a rex  please and thank you

**Comment by Auhrus** [comment]
Hi👋, unfortunately you have landed in the wrong repository. This repository is about a server for PathofTitans not about the game itself. I am not associated with PathofTitans or Alderon Games. This bug you reported has nothing to do with the Docker container provided by this repository. Please re-post your bug report here at https://github.com/Alderon-Games/pathoftitans-bugs/issues and answer the questions asked there in the template. This is the official repository of Alderon Games which is also linked in the game itself to report bugs.

Here you can find a description of what you have to consider when reporting.
https://github.com/Alderon-Games/pathoftitans-bugs/wiki/Reporting-Bugs-&-Format

**Comment by JuneduXisosaFegore** [comment]
thank you lol i found where to do it. Sorry hehehe
